# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8db658327e02128688a72b0217d448f3047ed3d6684648629fd18e433e50a56e386c94d0f16b56bc8e438bbb4f879ea1a42190067f833043cd5eeab1e748cee7

test:
  secret_key_base: 63c44608dc562e23add9fbe2b3ddc6598c40b4061b4adf79141ccda1ee86b409544d3c340919c5303817326dae2616ca98002631211762f20e4a98e85344c728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
